name: Emulator & Appium Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # ✅ Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create udev rules directory
        run: |
          sudo mkdir -p /etc/udev/rules.d/

      # ✅ Enable KVM for emulator acceleration
      - name: Enable KVM
        run: |
          sudo apt-get update
          sudo apt-get install -y udev
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # ✅ Add Android Platform Tools to PATH
      - name: Add Android Platform Tools to PATH
        run: echo "/usr/local/android-sdk/platform-tools" >> $GITHUB_PATH

      # ✅ Start Android Emulator with consistent API version (34)
      - name: Start Emulator and Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
            api-level: 34
            target: google_apis
            arch: x86_64
            disable-animations: true
            emulator-options: "-no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none"
            force-avd-creation: true
            cores: 2
            avd-name: test
            emulator-boot-timeout: 600
            emulator-port: 5554
            script: |
                echo "project list"
                ls -la
                echo "Emulator started. Running tests..."
                # Install dependencies, build APK, etc.
                echo "Installing Node.js dependencies..."
                npm install
                echo "Building Android APK..."
                npx cordova platform add android
                npx cordova build android --debug
                # Set the desired Chromedriver version for Chrome 113
                # CHROMEDRIVER_VERSION=113.0.5672.63
                # echo "Downloading Chromedriver version ${CHROMEDRIVER_VERSION}..."
                # wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
                # unzip chromedriver_linux64.zip
                # chmod +x chromedriver
                # ls -la
                # Start Appium Server in background
                echo "Starting Appium Server..."
                nohup npx appium --base-path /wd/hub > appium.log 2>&1 &
                sleep 10
                # Run WebdriverIO tests
                echo "Running WebdriverIO tests..."
                npx wdio run wdio.conf.js

    #   # ✅ Install Node.js dependencies
    #   - name: Install Dependencies
    #     run: npm install

    #   # ✅ Build Android APK (using Cordova in debug mode)
    #   - name: Build Android APK
    #     run: |
    #       npx cordova platform add android
    #       npx cordova build android --debug

    #   # ✅ Start Appium Server in headless mode
    #   - name: Start Appium Server
    #     run: |
    #       nohup npx appium --base-path /wd/hub > appium.log 2>&1 &
    #       sleep 10  # Wait for Appium to fully start

    #   # ✅ Run WebdriverIO (Appium) tests
    #   - name: Run WebdriverIO Tests
    #     run: npx wdio run wdio.conf.js

      # ✅ On failure, upload Appium logs for debugging
      - name: Upload Appium Logs on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: appium-logs
          path: appium.log
          retention-days: 7
