name: Android Emulator Tests

on: [push, pull_request]

jobs:
  test:
    # If Ubuntu 24 is available, you can use it here.
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # This step downloads and starts the Android emulator.
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          disable-animations: true
          # The action automatically creates and starts an AVD in headless mode.

      # Now you can run your instrumented tests.
      - name: Run instrumented tests
        run: ./gradlew connectedAndroidTest
